version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - INTELX_API_KEY=${INTELX_API_KEY}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./server.py:/app/server.py:ro 
    restart: unless-stopped
