version: '3.8'

services:
  intelligence-x-mcp:
    build: .
    container_name: intelx-mcp-server
    ports:
      - "8000:8000"
    environment:
      - INTELX_API_KEY=${INTELX_API_KEY}
      - INTELX_API_URL=${INTELX_API_URL:-https://2.intelx.io}
      - PORT=8000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge